# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MNGA.xcodeproj",
    )
    add_git_tag
    push_to_git_remote
    build_app(scheme: "MNGA (iOS)")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
