# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build MNGA"
  lane :build do
    build_app(scheme: "MNGA")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    if ENV["CI"]
      setup_ci

      app_store_connect_api_key
      # key_id:      APP_STORE_CONNECT_API_KEY_KEY_ID
      # key_content: APP_STORE_CONNECT_API_KEY_KEY
      # issuer_id:   APP_STORE_CONNECT_API_KEY_ISSUER_ID

      match(
        type: "appstore",
        # BugenZhao:<pat>
        git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      )
    else
      match(type: "appstore")
    end

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MNGA.xcodeproj",
    )

    build_app(scheme: "MNGA")

    changelog = changelog_from_git_commits(
      date_format: "short",
    )

    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: ["Nightly", "GitHub", "NGA"], # all groups
    )

    add_git_tag
    push_git_tags
  end
end
