# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    if ENV["CI"]
      setup_ci

      app_store_connect_api_key
      # key_id:      APP_STORE_CONNECT_API_KEY_KEY_ID
      # key_content: APP_STORE_CONNECT_API_KEY_KEY
      # issuer_id:   APP_STORE_CONNECT_API_KEY_ISSUER_ID

      match(
        type: "appstore",
        git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      )
    else
      match(type: "appstore")
    end

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MNGA.xcodeproj",
    )

    build_app(scheme: "MNGA (iOS)")

    upload_to_testflight(skip_waiting_for_build_processing: true)

    add_git_tag
    push_git_tags
  end
end
