[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
once_cell = "1"
protos = { path = "../protos" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
