<?xml version="1.0" encoding="GB18030"?>
<root>
    <__CU>
        <uid>41417929</uid>
        <group_bit>98528</group_bit>
        <admincheck></admincheck>
        <rvrc>15</rvrc>
    </__CU>
    <__GLOBAL>
        <_ATTACH_BASE_VIEW>img.nga.178.com/attachments</_ATTACH_BASE_VIEW>
    </__GLOBAL>
    <__U>
        <item>
            <uid>60673443</uid>
            <username>发牌员让我上次传说</username>
            <credit>135537152</credit>
            <medal></medal>
            <reputation>134_35,198_1,61_0</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1563771628</regdate>
            <mute_time></mute_time>
            <postnum>703</postnum>
            <rvrc>10</rvrc>
            <money>400</money>
            <thisvisit>1762720960</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135537152</bit_data>
        </item>
        <item>
            <uid>43121986</uid>
            <username>斯卡哈十七岁</username>
            <credit>1318912</credit>
            <medal></medal>
            <reputation>47_30,19_-595,65_-300</reputation>
            <groupid>-1</groupid>
            <memberid>42</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/d42/91f/002/43121986_1.jpg?68</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1533259418</regdate>
            <mute_time></mute_time>
            <postnum>893</postnum>
            <rvrc>-10</rvrc>
            <money>15861</money>
            <thisvisit>1762653760</thisvisit>
            <signature>人生五十年，与天地长久相较，如梦又似幻；一度得生者，岂有不灭者乎？</signature>
            <nickname></nickname>
            <bit_data>1318912</bit_data>
        </item>
        <item>
            <uid>60168972</uid>
            <username>咕嘿</username>
            <credit>135528960</credit>
            <medal></medal>
            <reputation>61_4,245_30,65_30,87_15,111_45</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1546244807</regdate>
            <mute_time></mute_time>
            <postnum>971</postnum>
            <rvrc>10</rvrc>
            <money>13100</money>
            <thisvisit>1762685179</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135528960</bit_data>
        </item>
        <item>
            <uid>66292096</uid>
            <username>速食面包</username>
            <credit>135266304</credit>
            <medal></medal>
            <reputation>61_11</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1729096193</regdate>
            <mute_time></mute_time>
            <postnum>631</postnum>
            <rvrc>10</rvrc>
            <money>900</money>
            <thisvisit>1762683949</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135266304</bit_data>
        </item>
        <item>
            <uid>551854</uid>
            <username>lovefmm614</username>
            <credit>169157120</credit>
            <medal></medal>
            <reputation>16_30,97_60,61_1</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/bae/086/000/551854_0.png?5564</avatar>
            <yz>4</yz>
            <site></site>
            <honor> 1567530942 被集火的非洲大领主</honor>
            <regdate>1175087546</regdate>
            <mute_time></mute_time>
            <postnum>3092</postnum>
            <rvrc>11</rvrc>
            <money>44911</money>
            <thisvisit>1762664691</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>169157120</bit_data>
        </item>
        <item>
            <uid>62513872</uid>
            <username>豆包爱吃猫</username>
            <credit>169091584</credit>
            <medal></medal>
            <reputation>61_84,94_15,87_-300</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/2d0/b9e/003/62513872_0.jpg?61</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1600274191</regdate>
            <mute_time></mute_time>
            <postnum>11352</postnum>
            <rvrc>10</rvrc>
            <money>2500</money>
            <thisvisit>1762666076</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>169091584</bit_data>
        </item>
        <item>
            <uid>21293009</uid>
            <username>resurvive</username>
            <credit>135536640</credit>
            <medal></medal>
            <reputation>61_14</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>http://img.nga.178.com/avatars/2002/7d1/44e/001/21293009_0.jpg?39</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1361174477</regdate>
            <mute_time></mute_time>
            <postnum>582</postnum>
            <rvrc>10</rvrc>
            <money>19900</money>
            <thisvisit>1762720773</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135536640</bit_data>
        </item>
        <item>
            <uid>65812193</uid>
            <username>碳烤生加蒜泥</username>
            <credit>135275008</credit>
            <medal></medal>
            <reputation>61_260,-7_-150</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1717799663</regdate>
            <mute_time></mute_time>
            <postnum>3177</postnum>
            <rvrc>10</rvrc>
            <money>19900</money>
            <thisvisit>1762740162</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135275008</bit_data>
        </item>
        <item>
            <uid>62865134</uid>
            <username>八百新日暮里</username>
            <credit>135536640</credit>
            <medal></medal>
            <reputation>61_1,-7_15</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/eee/bf3/003/62865134_0.png?12</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1609989161</regdate>
            <mute_time></mute_time>
            <postnum>562</postnum>
            <rvrc>10</rvrc>
            <money>600</money>
            <thisvisit>1762724320</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135536640</bit_data>
        </item>
        <item>
            <uid>63850993</uid>
            <username>最终肥宅兵器</username>
            <credit>135266817</credit>
            <medal></medal>
            <reputation>61_8,130_300</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1640701239</regdate>
            <mute_time></mute_time>
            <postnum>3437</postnum>
            <rvrc>10</rvrc>
            <money>7840</money>
            <thisvisit>1762708094</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135266817</bit_data>
        </item>
        <item>
            <uid>61238928</uid>
            <username>kclu8008</username>
            <credit>135536640</credit>
            <medal></medal>
            <reputation>61_5</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1572323453</regdate>
            <mute_time></mute_time>
            <postnum>611</postnum>
            <rvrc>10</rvrc>
            <money>2000</money>
            <thisvisit>1762724348</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135536640</bit_data>
        </item>
        <item>
            <uid>43307902</uid>
            <username>霸王艾茵哈特</username>
            <credit>704909824</credit>
            <medal></medal>
            <reputation>61_38,128_-150,167_15,134_30,130_10,199_35,196_10,215_15</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1536610966</regdate>
            <mute_time></mute_time>
            <postnum>5917</postnum>
            <rvrc>0</rvrc>
            <money>0</money>
            <thisvisit>1762695320</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>704909824</bit_data>
        </item>
        <item>
            <uid>1087837</uid>
            <username>Antoc</username>
            <credit>169091584</credit>
            <medal></medal>
            <reputation>102_-300,19_-75,61_0,64_-150,-7_-735,147_-600,139_-150</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/95d/109/000/1087837_0.jpg?84</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1217647934</regdate>
            <mute_time></mute_time>
            <postnum>15888</postnum>
            <rvrc>10</rvrc>
            <money>16863</money>
            <thisvisit>1762714646</thisvisit>
            <signature>不要转移支付！&lt;br/&gt;&lt;br/&gt;名词解释：无孩爱猫女/哈基美/CMG/Childless Moggoy
                Girl&lt;br/&gt;&lt;br/&gt;饿死的木构 才是好木构</signature>
            <nickname></nickname>
            <bit_data>169091584</bit_data>
        </item>
        <item>
            <uid>34859487</uid>
            <username>上古之神的陪伴</username>
            <credit>169091073</credit>
            <medal></medal>
            <reputation>-7_-600,109_-150,61_1,92_-150</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>http://img.nga.178.com/avatars/2002/9df/13e/002/34859487_0.png?89</avatar>
            <yz>4</yz>
            <site></site>
            <honor> 1567530942 被守尸的新手肥肥</honor>
            <regdate>1425493217</regdate>
            <mute_time></mute_time>
            <postnum>4993</postnum>
            <rvrc>11</rvrc>
            <money>20000</money>
            <thisvisit>1762679799</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>169091073</bit_data>
        </item>
        <item>
            <uid>65789895</uid>
            <username>上午拿铁下午美式</username>
            <credit>135275008</credit>
            <medal></medal>
            <reputation>61_259,85_-300</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/fc7/ebd/003/65789895_0.jpg?81</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1716874522</regdate>
            <mute_time></mute_time>
            <postnum>4400</postnum>
            <rvrc>10</rvrc>
            <money>19900</money>
            <thisvisit>1762702453</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135275008</bit_data>
        </item>
        <item>
            <uid>62246094</uid>
            <username>逃避虽说可耻但还有用</username>
            <credit>135537216</credit>
            <medal></medal>
            <reputation>61_515,199_60,-7_45</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/cce/b5c/003/62246094_0.jpg?51</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1591394336</regdate>
            <mute_time></mute_time>
            <postnum>17242</postnum>
            <rvrc>10</rvrc>
            <money>19900</money>
            <thisvisit>1762674915</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135537216</bit_data>
            <group_bit_buf>2048</group_bit_buf>
            <buffs>
                <item>
                    <item>
                        <item>1313402</item>
                        <item>129</item>
                        <item>0</item>
                        <item>62246094</item>
                        <item>1760491967</item>
                        <item>1763304263</item>
                        <item>2048</item>
                        <item>0</item>
                    </item>
                </item>
                <item>
                    <item>
                        <item>1335948</item>
                        <item>120</item>
                        <item>62246094</item>
                        <item>62246094</item>
                        <item>1754843932</item>
                        <item>1849451932</item>
                        <item>8</item>
                        <item>1</item>
                        <item></item>
                        <item>..res..</item>
                    </item>
                </item>
            </buffs>
        </item>
        <item>
            <uid>66971867</uid>
            <username>Veldrain</username>
            <credit>135266304</credit>
            <medal></medal>
            <reputation>61_6</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/8db/fde/003/66971867_0.jpg?49</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1761465066</regdate>
            <mute_time></mute_time>
            <postnum>116</postnum>
            <rvrc>10</rvrc>
            <money>600</money>
            <thisvisit>1762683082</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>135266304</bit_data>
        </item>
        <item>
            <uid>41712683</uid>
            <username>miyannn</username>
            <credit>1311232</credit>
            <medal></medal>
            <reputation>128_1250,137_20,96_-90,139_30</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar></avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1501555070</regdate>
            <mute_time></mute_time>
            <postnum>5994</postnum>
            <rvrc>6</rvrc>
            <money>20757</money>
            <thisvisit>1762737391</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>1311232</bit_data>
        </item>
        <item>
            <uid>2047757</uid>
            <username>纳斯利亚海王</username>
            <credit>169091137</credit>
            <medal>347,207,56,65</medal>
            <reputation>75_15,61_1,82_60,-7_50</reputation>
            <groupid>-1</groupid>
            <memberid>39</memberid>
            <avatar>https://img.nga.178.com/avatars/2002/f0d/1f3/000/2047757_0.jpg?7</avatar>
            <yz>4</yz>
            <site></site>
            <honor></honor>
            <regdate>1242268597</regdate>
            <mute_time></mute_time>
            <postnum>1115</postnum>
            <rvrc>10</rvrc>
            <money>4135</money>
            <thisvisit>1762738447</thisvisit>
            <signature></signature>
            <nickname></nickname>
            <bit_data>169091137</bit_data>
            <remark>
                <item>
                    <item>45284</item>
                    <item>1</item>
                    <item>1762727943</item>
                    <item>2</item>
                    <item>sv wow_classic rl 觅心者 re heartseeker ch 雷文德斯绿茶 rc 血精灵 cl 圣骑士 fa 部落 tl av
                        3280 it 276 mh 0 gd FEMALE ci pl </item>
                </item>
            </remark>
            <buffs>
                <item>
                    <item>
                        <item>1521370</item>
                        <item>120</item>
                        <item>2047757</item>
                        <item>2047757</item>
                        <item>1740124245</item>
                        <item>1834732245</item>
                        <item>8</item>
                        <item>1</item>
                        <item></item>
                        <item>..res..</item>
                    </item>
                </item>
            </buffs>
        </item>
        <__GROUPS>
            <item>
                <item>学徒</item>
                <item>98528</item>
                <item>39</item>
            </item>
            <item>
                <item>警告等级1</item>
                <item>98528</item>
                <item>42</item>
            </item>
        </__GROUPS>
        <__MEDALS>
            <item>
                <item>347.gif</item>
                <item>企鹅帽</item>
                <item>企鹅帽</item>
                <item>347</item>
            </item>
            <item>
                <item>207.gif</item>
                <item>爆竹声中旧岁除</item>
                <item>一支红杏出墙来</item>
                <item>207</item>
            </item>
            <item>
                <item>_55.gif</item>
                <item>NGA七周年</item>
                <item>艾泽拉斯国家地理七周年成长历程的见证者。</item>
                <item>56</item>
            </item>
            <item>
                <item>65.gif</item>
                <item>杯具了！</item>
                <item>艾泽拉斯国家地理对于您因购买七周年纪念刊而遭遇各种杯具事件深表歉意。</item>
                <item>65</item>
            </item>
        </__MEDALS>
        <__REPUTATIONS>
            <item>
                <item>
                    <item>60673443</item>
                    <item>0</item>
                </item>
                <item>
                    <item>43121986</item>
                    <item>0</item>
                </item>
                <item>
                    <item>60168972</item>
                    <item>0</item>
                </item>
                <item>
                    <item>66292096</item>
                    <item>0</item>
                </item>
                <item>
                    <item>551854</item>
                    <item>0</item>
                </item>
                <item>
                    <item>62513872</item>
                    <item>0</item>
                </item>
                <item>
                    <item>21293009</item>
                    <item>0</item>
                </item>
                <item>
                    <item>65812193</item>
                    <item>0</item>
                </item>
                <item>
                    <item>62865134</item>
                    <item>0</item>
                </item>
                <item>
                    <item>63850993</item>
                    <item>0</item>
                </item>
                <item>
                    <item>61238928</item>
                    <item>0</item>
                </item>
                <item>
                    <item>43307902</item>
                    <item>0</item>
                </item>
                <item>
                    <item>1087837</item>
                    <item>-450</item>
                </item>
                <item>
                    <item>34859487</item>
                    <item>0</item>
                </item>
                <item>
                    <item>65789895</item>
                    <item>0</item>
                </item>
                <item>
                    <item>62246094</item>
                    <item>0</item>
                </item>
                <item>
                    <item>66971867</item>
                    <item>0</item>
                </item>
                <item>
                    <item>41712683</item>
                    <item>0</item>
                </item>
                <item>
                    <item>2047757</item>
                    <item>0</item>
                </item>
                <name>用户圣光礼赞(7955747)的声望</name>
                <id>-7955747</id>
            </item>
        </__REPUTATIONS>
    </__U>
    <__R>
        <item>
            <content>
                还有半小时她要起床上班了，我在厕所12点坐到现在一直在翻她银行卡明细，确定了她借了我俩都还不清的债。&lt;br/&gt;最开始知道她借钱是在今年5月，那天她一声不吭跑去广州，问她去干嘛她却模糊其辞，我怀疑她出轨了与于是逼问她，以分手相逼才哭着给我看借钱记录，十万，但是到手是八万多。我质问她借钱干嘛，她说工资不够用了(我俩都有正常工作)，我说不够找我呀，我还帮她理到底哪花了这么多钱，我已经感觉到一丝不对了但也没追究下去了。&lt;br/&gt;今天我下班回来后她睡着了，我于是拿她手机玩，突然想看下她剩多少钱，验证下我的猜想对不对。打卡银行app一看剩一万五，我的心脏瞬间有种被憋住的感觉。于是我就搜大额流水明细，发现了每个月都支出好多个好几千，狗东、蚂蚁、音符…各个平台都有，数额加起来几十万而且都没还完，五月借的那个十万才只换还了几千。&lt;br/&gt;我真的感觉天塌了，她早住在我家了，但我还没见她父母，本来我觉得她就是我后半辈子的人，现在看到她背负的债我犹豫了，退缩了。可她和我是那么般配，在此之前我觉得她三观非常正的，虽然她家庭不是那么富裕，但能过日子就很幸福了。我感觉我坐在马桶上在写小说一样，有点无聊的爱情小说，可这无聊的小说确实发生在我身上了，变得那么惊悚那么得手足无措&lt;br/&gt;[img]./mon_202511/10/-4qiozQwirp-44vvZbT3cSqo-zk.jpg.medium.jpg[/img]&lt;br/&gt;[img]./mon_202511/10/-4qiozQwirp-9sm1ZfT3cSqo-zk.jpg.medium.jpg[/img]&lt;br/&gt;[img]./mon_202511/10/-4qiozQwirp-bxeaZbT3cSqo-zk.jpg.medium.jpg[/img]</content>
            <alterinfo></alterinfo>
            <tid>45550667</tid>
            <score>0</score>
            <score_2>0</score_2>
            <postdate>2025-11-10 05:21</postdate>
            <authorid>60673443</authorid>
            <subject>人在厕所已经崩溃，女友借了几十万以贷还贷</subject>
            <type>33562628</type>
            <fid>-7955747</fid>
            <pid>0</pid>
            <recommend>0</recommend>
            <follow>0</follow>
            <lou>0</lou>
            <content_length>1182</content_length>
            <attachs>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-44vvZbT3cSqo-zk.jpg</attachurl>
                    <size>109</size>
                    <type>img</type>
                    <subid>0</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-44vvZbT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-9sm1ZfT3cSqo-zk.jpg</attachurl>
                    <size>147</size>
                    <type>img</type>
                    <subid>1</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-9sm1ZfT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-bxeaZbT3cSqo-zk.jpg</attachurl>
                    <size>106</size>
                    <type>img</type>
                    <subid>2</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-bxeaZbT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
            </attachs>
            <comment_id>
                <item>847141658</item>
                <item>847149308</item>
            </comment_id>
            <from_client>7 iOS</from_client>
            <item>,847128360,847128429,847128371,847128367</item>
            <postdatetimestamp>1762723279</postdatetimestamp>
            <comment>
                <item>
                    <pid>847141658</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>41712683</authorid>
                    <type>1</type>
                    <score>7</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 09:32</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>
                        [b]Reply to [tid=45550667]Topic[/tid] Post by
                        [uid=60673443]发牌员让我上次传说[/uid] (2025-11-10
                        05:21)[/b]&lt;br/&gt;&lt;br/&gt;龟男，知道她借十万时就该把隐瞒的债务缘由全都挖出来，不对劲直接就跑路了，还搁着心存侥幸龟龟还贷，装作鸵鸟不闻不问，现在爆大雷了就知道发帖找网友问方法了？好死，利滚利套路贷就是无底洞</content>
                    <lou>0</lou>
                    <content_length>180</content_length>
                    <comment_to_id>-1</comment_to_id>
                    <from_client>0 /</from_client>
                    <postdatetimestamp>1762738374</postdatetimestamp>
                </item>
                <item>
                    <pid>847149308</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>2047757</authorid>
                    <type>1</type>
                    <score>1</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 10:25</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>[b]Reply to [tid=45550667]Topic[/tid] Post by
                        [uid=60673443]发牌员让我上次传说[/uid] (2025-11-10
                        05:21)[/b]&lt;br/&gt;&lt;br/&gt;你还没说她一声不吭去广州干啥去了，不会是想办法还债去了吧，哥们你得搞清楚啊，别让自己吃亏</content>
                    <lou>0</lou>
                    <content_length>88</content_length>
                    <comment_to_id>-1</comment_to_id>
                    <from_client>0 /</from_client>
                    <postdatetimestamp>1762741540</postdatetimestamp>
                </item>
            </comment>
            <hotreply_id>
                <item></item>
                <item>847128360</item>
                <item>847128429</item>
                <item>847128371</item>
                <item>847128367</item>
            </hotreply_id>
            <hotreply>
                <item>
                    <pid>847128360</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>43121986</authorid>
                    <type>0</type>
                    <score>913</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 05:22</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>跑路，不跑没人同情你</content>
                    <lou>1</lou>
                    <content_length>20</content_length>
                    <from_client>100 /</from_client>
                    <postdatetimestamp>1762723333</postdatetimestamp>
                </item>
                <item>
                    <pid>847128429</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>21293009</authorid>
                    <type>0</type>
                    <score>543</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 05:31</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>
                        重点不是借钱，重点是为啥她每个月开支这么大？如果借钱是为了解决急用(比如治病等)，只要慢慢还清就没事了。但看你说的她每个月都要在各大平台花掉好几千，这种铺张浪费的习惯很难改，就算这次还清了，下次还会再继续借。[s:a2:不明觉厉]</content>
                    <lou>6</lou>
                    <content_length>204</content_length>
                    <from_client>8 Android</from_client>
                    <postdatetimestamp>1762723895</postdatetimestamp>
                </item>
                <item>
                    <pid>847128371</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>551854</authorid>
                    <type>0</type>
                    <score>470</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 05:23</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>又不是你老婆，就算是你老婆也不是夫妻共同债务，不知道你在这慌个啥。</content>
                    <lou>4</lou>
                    <content_length>66</content_length>
                    <from_client>8 Android</from_client>
                    <postdatetimestamp>1762723434</postdatetimestamp>
                </item>
                <item>
                    <pid>847128367</pid>
                    <fid>-7955747</fid>
                    <tid>45550667</tid>
                    <authorid>60168972</authorid>
                    <type>0</type>
                    <score>383</score>
                    <score_2>0</score_2>
                    <recommend>0</recommend>
                    <postdate>2025-11-10 05:23</postdate>
                    <subject></subject>
                    <alterinfo></alterinfo>
                    <content>没结婚你怕什么[s:a2:不明觉厉]</content>
                    <lou>2</lou>
                    <content_length>12</content_length>
                    <from_client>8 Android</from_client>
                    <postdatetimestamp>1762723403</postdatetimestamp>
                </item>
            </hotreply>
        </item>
        <item>
            <pid>847128360</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>43121986</authorid>
            <type>0</type>
            <score>913</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:22</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>跑路，不跑没人同情你</content>
            <lou>1</lou>
            <content_length>20</content_length>
            <from_client>100 /</from_client>
            <postdatetimestamp>1762723333</postdatetimestamp>
        </item>
        <item>
            <pid>847128367</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>60168972</authorid>
            <type>0</type>
            <score>383</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:23</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>没结婚你怕什么[s:a2:不明觉厉]</content>
            <lou>2</lou>
            <content_length>12</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762723403</postdatetimestamp>
        </item>
        <item>
            <pid>847128370</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>66292096</authorid>
            <type>0</type>
            <score>57</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:23</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>先活下来再求优质 拖着只会把你俩拖死</content>
            <lou>3</lou>
            <content_length>34</content_length>
            <from_client>0 /</from_client>
            <postdatetimestamp>1762723430</postdatetimestamp>
        </item>
        <item>
            <pid>847128371</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>551854</authorid>
            <type>0</type>
            <score>470</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:23</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>又不是你老婆，就算是你老婆也不是夫妻共同债务，不知道你在这慌个啥。</content>
            <lou>4</lou>
            <content_length>66</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762723434</postdatetimestamp>
        </item>
        <item>
            <pid>847128428</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>62513872</authorid>
            <type>0</type>
            <score>40</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:31</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>看看戒社&lt;br/&gt;&lt;br/&gt;快跑</content>
            <lou>5</lou>
            <content_length>12</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762723880</postdatetimestamp>
        </item>
        <item>
            <pid>847128429</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>21293009</authorid>
            <type>0</type>
            <score>543</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:31</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>
                重点不是借钱，重点是为啥她每个月开支这么大？如果借钱是为了解决急用(比如治病等)，只要慢慢还清就没事了。但看你说的她每个月都要在各大平台花掉好几千，这种铺张浪费的习惯很难改，就算这次还清了，下次还会再继续借。[s:a2:不明觉厉]</content>
            <lou>6</lou>
            <content_length>204</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762723895</postdatetimestamp>
        </item>
        <item>
            <pid>847128484</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>65812193</authorid>
            <type>0</type>
            <score>90</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:37</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>说真的，现在这个时代，网贷和赌狗属于一类人</content>
            <lou>7</lou>
            <content_length>42</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762724259</postdatetimestamp>
        </item>
        <item>
            <pid>847128509</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>62865134</authorid>
            <type>0</type>
            <score>15</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:40</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>又不是你欠的有啥好哭的，抗火车跑路呗[s:ac:茶]</content>
            <lou>8</lou>
            <content_length>34</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762724414</postdatetimestamp>
        </item>
        <item>
            <pid>847128519</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>63850993</authorid>
            <type>0</type>
            <score>68</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:41</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>她自己习惯了花这么多钱的生活水平了，你不分又爆不出金币来，她自然而然也会踢了你</content>
            <lou>9</lou>
            <content_length>78</content_length>
            <from_client>0 /</from_client>
            <postdatetimestamp>1762724487</postdatetimestamp>
        </item>
        <item>
            <pid>847128521</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>60673443</authorid>
            <type>0</type>
            <score>0</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:41</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>
                [quote][pid=847128429,45550667,1]Reply[/pid] [b]Post by
                [uid=21293009]resurvive[/uid] (2025-11-10
                05:31):[/b]&lt;br/&gt;&lt;br/&gt;重点不是借钱，重点是为啥她每个月开支这么大？如果借钱是为了解决急用(比如治病等)，只要慢慢还清就没事了。但看你说的她每个月都要在各大平台花掉好几千，这种铺张浪费的习惯很难改，就算这次还清了，下次还会再继续借。[s:a2:不明觉厉][/quote]&lt;br/&gt;&lt;br/&gt;她下班就回家，偶尔去和朋友吃个饭玩一下，再就是买买东西，我也搞不清楚花去哪了，开销最大的就是还款，我怀疑是以贷还贷利滚利欠下来，哪年开始借的还不清楚</content>
            <lou>10</lou>
            <content_length>153</content_length>
            <from_client>7 iOS</from_client>
            <reply_to>847128429</reply_to>
            <postdatetimestamp>1762724505</postdatetimestamp>
        </item>
        <item>
            <pid>847128542</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>61238928</authorid>
            <type>0</type>
            <score>69</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:44</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>最后跟你要彩礼填窟窿，你考虑清楚</content>
            <lou>11</lou>
            <content_length>32</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762724681</postdatetimestamp>
        </item>
        <item>
            <pid>847128554</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>60673443</authorid>
            <type>0</type>
            <score>0</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:45</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>
                [quote][pid=847128371,45550667,1]Reply[/pid] [b]Post by
                [uid=551854]lovefmm614[/uid] (2025-11-10
                05:23):[/b]&lt;br/&gt;&lt;br/&gt;又不是你老婆，就算是你老婆也不是夫妻共同债务，不知道你在这慌个啥。[/quote]&lt;br/&gt;&lt;br/&gt;我不是慌，我是可惜这些年的感情就因为这个断了，除了这件事她真的对上我的所有，除了领证真的就是夫妻了</content>
            <lou>12</lou>
            <content_length>103</content_length>
            <from_client>7 iOS</from_client>
            <reply_to>847128371</reply_to>
            <postdatetimestamp>1762724753</postdatetimestamp>
        </item>
        <item>
            <pid>847128561</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>43307902</authorid>
            <type>0</type>
            <score>76</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:46</postdate>
            <subject></subject>
            <alterinfo>[E1762724876 0 0] </alterinfo>
            <content>想清楚，这怎么是你女友呢 &lt;br/&gt;另外记得去拉一下支付宝和微信记录，看看有没有688 388 588这种金额怪异的消费</content>
            <lou>13</lou>
            <content_length>95</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762724776</postdatetimestamp>
        </item>
        <item>
            <pid>847128582</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>1087837</authorid>
            <type>64</type>
            <score>99</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:48</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>
                跟你说了蝈籹人均化债仙人[s:ac:哭笑]&lt;br/&gt;从出生就精准培育的消费主义牲畜&lt;br/&gt;&lt;br/&gt;你以为骗你的吗[s:ac:哭笑]</content>
            <lou>14</lou>
            <content_length>64</content_length>
            <from_client>0 /</from_client>
            <postdatetimestamp>1762724898</postdatetimestamp>
        </item>
        <item>
            <pid>847128589</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>60673443</authorid>
            <type>0</type>
            <score>0</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:49</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>
                [quote][pid=847128519,45550667,1]Reply[/pid] [b]Post by
                [uid=63850993]最终肥宅兵器[/uid] (2025-11-10
                05:41):[/b]&lt;br/&gt;&lt;br/&gt;她自己习惯了花这么多钱的生活水平了，你不分又爆不出金币来，她自然而然也会踢了你[/quote]&lt;br/&gt;&lt;br/&gt;可在一起这些年她没有索要过任何金钱啊，吃饭买东西我俩都是很随意的，我想付就我付，她想付就她来，也不aa。我俩就是单纯的爱</content>
            <lou>15</lou>
            <content_length>123</content_length>
            <from_client>7 iOS</from_client>
            <reply_to>847128519</reply_to>
            <postdatetimestamp>1762724979</postdatetimestamp>
        </item>
        <item>
            <pid>847128601</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>34859487</authorid>
            <type>0</type>
            <score>0</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:51</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>我知道你的心情，有时候很爱一个人，就想着帮他背负一切，哪怕搭上自己也要帮助对方。</content>
            <lou>16</lou>
            <content_length>80</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762725108</postdatetimestamp>
        </item>
        <item>
            <pid>847128613</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>65789895</authorid>
            <type>0</type>
            <score>51</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:52</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>换位思考，你借了几十万她会……？</content>
            <lou>17</lou>
            <content_length>32</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762725175</postdatetimestamp>
        </item>
        <item>
            <pid>847128622</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>62246094</authorid>
            <type>0</type>
            <score>50</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:53</postdate>
            <subject></subject>
            <alterinfo></alterinfo>
            <content>如果她提出去东南亚或中东等地旅游&lt;br/&gt;当心她把你给卖了。。。。[s:a2:你已经死了]</content>
            <lou>18</lou>
            <content_length>54</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762725237</postdatetimestamp>
        </item>
        <item>
            <pid>847128626</pid>
            <fid>-7955747</fid>
            <tid>45550667</tid>
            <authorid>66971867</authorid>
            <type>0</type>
            <score>14</score>
            <score_2>0</score_2>
            <recommend>0</recommend>
            <postdate>2025-11-10 05:54</postdate>
            <subject></subject>
            <alterinfo>[E1762725322 0 0] </alterinfo>
            <content>别人借钱跟你有啥关系，这也能崩溃，你是什么看到有人出事就哭一天的圣人？</content>
            <lou>19</lou>
            <content_length>70</content_length>
            <from_client>8 Android</from_client>
            <postdatetimestamp>1762725260</postdatetimestamp>
        </item>
    </__R>
    <__T>
        <fid>-7955747</fid>
        <tid>45550667</tid>
        <topic_misc></topic_misc>
        <subject>人在厕所已经崩溃，女友借了几十万以贷还贷</subject>
        <locked>0</locked>
        <recommend>0</recommend>
        <quote_to></quote_to>
        <quote_from>0</quote_from>
        <type>8196</type>
        <replies>431</replies>
        <authorid>60673443</authorid>
        <postdate>1762723279</postdate>
        <lastpost>1762743698</lastpost>
        <jdata></jdata>
        <author>发牌员让我上次传说</author>
        <lastposter>a504547638</lastposter>
        <digest>0</digest>
        <lastmodify>1762743698</lastmodify>
        <tpid>0</tpid>
        <post_misc_var>
            <content_length>1182</content_length>
            <fid>-7955747</fid>
            <attachs>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-44vvZbT3cSqo-zk.jpg</attachurl>
                    <size>109</size>
                    <type>img</type>
                    <subid>0</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-44vvZbT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-9sm1ZfT3cSqo-zk.jpg</attachurl>
                    <size>147</size>
                    <type>img</type>
                    <subid>1</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-9sm1ZfT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
                <item>
                    <attachurl>mon_202511/10/-4qiozQwirp-bxeaZbT3cSqo-zk.jpg</attachurl>
                    <size>106</size>
                    <type>img</type>
                    <subid>2</subid>
                    <url_utf8_org_name></url_utf8_org_name>
                    <dscp></dscp>
                    <path>mon_202511/10</path>
                    <name>-4qiozQwirp-bxeaZbT3cSqo-zk.jpg</name>
                    <ext>jpg</ext>
                    <thumb>120</thumb>
                </item>
            </attachs>
            <comment_id>,847141658,847149308</comment_id>
            <item>,847128360,847128429,847128371,847128367</item>
        </post_misc_var>
        <this_visit_rows>432</this_visit_rows>
    </__T>
    <__F>
        <custom_level>
            [{r:-501,n:&quot;离人&quot;},{r:-450,n:&quot;遗恨&quot;},{r:-300,n:&quot;负心&quot;},{r:-150,n:&quot;前任&quot;},{r:-1,n:&quot;过客&quot;},{r:0,n:&quot;酌客&quot;},{r:150,n:&quot;说书人&quot;},{r:1500,n:&quot;万人迷&quot;}]</custom_level>
        <name>晴风村</name>
    </__F>
    <__R__ROWS>20</__R__ROWS>
    <__R__ROWS_PAGE>20</__R__ROWS_PAGE>
    <__ROWS>432</__ROWS>
    <__PAGE>1</__PAGE>
</root>
